import { Injectable } from '@angular/core';
import { Housinglocation } from './housinglocation';
@Injectable({
  providedIn: 'root'
})
export class ProfiledoctorService {
  
  readonly baseUrl2 = 'https://picsum.photos/200/300';
  
  generateRandomImage() {
    const randomNumber = Math.floor(Math.random() * 1000); 
    return `${this.baseUrl2}?random=${randomNumber}`;
  }
  submitApplication(firstName: string, lastName: string, email: string, appointmentDate: string, appointmentTime: string) {
    console.log(`Application received: 
      First Name: ${firstName}, 
      Last Name: ${lastName}, 
      Email: ${email}, 
      Appointment Date: ${appointmentDate}, 
      Appointment Time: ${appointmentTime}`);

  }
  DoctorprofileList: Housinglocation [] = [
    {
      id: 1,
      name: 'Bennani Fatima',
      specialite: 'Dentiste, Esthétique dentaire, Endodontiste, Orthodontiste, Pédodontiste à Casablanca',
      city: 'casablanca',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: Math.floor(Math.random() * 100),
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: false,
      adomicile: false,
      adresse: '123 Rue Imaginaire' ,
      numtele: '+1234567890' ,
      numcabinet:'CAB-123',
    },
    {
      id: 2,
      name: 'El Kaddouri Samira',
      specialite: 'Gynécologue, Obstétricien à Marrakech',
      city: 'marrakech',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: Math.floor(Math.random() * 100),
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: false,
      adresse: '456 Dream Street' ,
      numtele: '+1234567890' ,
      numcabinet:'CAB-123',
    },
    {
      id: 3,
      name: 'Hassani Jamal',
      specialite: 'Cardiologue, Médecine interne à Asfi',
      city: 'asfi',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: Math.floor(Math.random() * 100),
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: false,
      adresse: '789 Enchanted Avenue' ,
      numtele: '+1234567890' ,
      numcabinet:'CAB-123',
    },
    {
      id: 4,
      name: 'Fassi Fatiha',
      specialite: 'Ophtalmologue à Casablanca',
      city: 'casablanca',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: Math.floor(Math.random() * 100),
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: false,
      adresse: '567 Starlight Lane' ,
      numtele: '+1234567890' ,
      numcabinet:'CAB-123',
    },
    {
      id: 5,
      name: 'Ouazzani Amine',
      specialite: 'Chirurgien plastique, Esthétique à Marrakech',
      city: 'marrakech',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: Math.floor(Math.random() * 100),
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: false,
      adresse: '890 Rainbow Road' ,
      numtele: '+1234567890' ,
      numcabinet:'CAB-123',
    },
    {
      id: 6,
      name: 'Ahmed El Amrani',
      specialite: 'Cardiologue',
      city: 'Casablanca',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 78,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: false,
      adomicile: true,
      adresse: '123 Avenue Hassan II, Casablanca',
      numtele: '+212123456789',
      numcabinet: 'CAB-123',
    },
    {
      id: 7,
      name: 'Fatima Zohra Berrada',
      specialite: 'Dermatologue',
      city: 'Marrakech',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 92,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: false,
      adresse: '789 Rue Mohammed V, Marrakech',
      numtele: '+212123456789',
      numcabinet: 'CAB-456',
    },
    {
      id: 8,
      name: 'Hamza Chraibi',
      specialite: 'Gynécologue',
      city: 'Rabat',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 65,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: true,
      adresse: '456 Avenue Mohamed VI, Rabat',
      numtele: '+212123456789',
      numcabinet: 'CAB-789',
    },
    {
      id: 9,
      name: 'Amina Lahbabi',
      specialite: 'Ophtalmologue',
      city: 'Fès',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 81,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: false,
      adomicile: false,
      adresse: '789 Rue des Almohades, Fès',
      numtele: '+212123456789',
      numcabinet: 'CAB-101',
    },
    {
      id: 10,
      name: 'Youssef Benjelloun',
      specialite: 'Orthopédiste',
      city: 'Tanger',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 73,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: false,
      adresse: '123 Avenue Moulay Youssef, Tanger',
      numtele: '+212123456789',
      numcabinet: 'CAB-202',
    },
    {
      id: 11,
      name: 'Naima Mernissi',
      specialite: 'Psychiatre',
      city: 'Agadir',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 87,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: true,
      adresse: '456 Avenue Al Massira, Agadir',
      numtele: '+212123456789',
      numcabinet: 'CAB-303',
    },
    {
      id: 12,
      name: 'Laila Touil',
      specialite: 'Pédiatre',
      city: 'Meknès',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 70,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: false,
      adomicile: false,
      adresse: '789 Rue Ibn Sina, Meknès',
      numtele: '+212123456789',
      numcabinet: 'CAB-404',
    },
    {
      id: 13,
      name: 'Rachid El Ghazi',
      specialite: 'Chirurgien dentiste',
      city: 'Oujda',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 76,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: false,
      adresse: '123 Boulevard Mohammed V, Oujda',
      numtele: '+212123456789',
      numcabinet: 'CAB-505',
    },
    {
      id: 14,
      name: 'Khadija Amine',
      specialite: 'Radiologue',
      city: 'Essaouira',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 68,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: false,
      adomicile: true,
      adresse: '456 Rue de lIndépendance, Essaouira',
      numtele: '+212123456789',
      numcabinet: 'CAB-606',
    },
    {
      id: 15,
      name: 'Karim El Fassi',
      specialite: 'Chirurgien général',
      city: 'Tétouan',
      title: 'Dr',
      photo: this.generateRandomImage(),
      Rdvconfirmer: 72,
      actes: [
        'Acte 1',
        'Acte 2',
        'Acte 3',
        'Acte 4',
        'Acte 5',
        'Acte 6',
        'Acte 7',
        'Acte 8',
        'Acte 9',
        'Acte 10',
        'Acte 11',
        'Acte 12'
      ],
      cabinet: true,
      videocall: true,
      adomicile: false,
      adresse: '789 Avenue Mohammed V, Tétouan',
      numtele: '+212123456789',
      numcabinet: 'CAB-707',
    },
  ];
  getAllProfile(): Housinglocation[] {
    return this.DoctorprofileList;
  }

  getProfileById(id: number): Housinglocation | undefined {
    return this.DoctorprofileList.find(housingLocation => housingLocation.id === id);
  }

}


